# Generated by Django 3.2 on 2022-11-12 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manual_Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_published', models.BooleanField(default=True, verbose_name='опубликовано')),
            ],
            options={
                'verbose_name': 'раздел',
                'verbose_name_plural': 'разделы',
            },
        ),
        migrations.CreateModel(
            name='Manual_Infoblock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='материал по теме')),
                ('is_published', models.BooleanField(default=True, verbose_name='опубликовано')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infoblock', to='py_compiler.manual_section', verbose_name='раздел')),
            ],
            options={
                'verbose_name': 'блок статьи',
                'verbose_name_plural': 'блоки статей',
            },
        ),
    ]
