# Generated by Django 3.2 on 2022-11-12 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('py_compiler', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manual_infoblock',
            options={'verbose_name': 'статья', 'verbose_name_plural': 'статьи'},
        ),
        migrations.AddField(
            model_name='manual_infoblock',
            name='block_name',
            field=models.CharField(default=12, max_length=150, unique=True, verbose_name='название'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='manual_section',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='название'),
        ),
    ]
