# Generated by Django 3.2 on 2022-11-16 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pytpretator', '0002_auto_20221112_1454'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(max_length=150, verbose_name='ссылка на видео')),
                ('is_published', models.BooleanField(default=True, verbose_name='отображать')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videoexample', to='pytpretator.manual_infoblock', verbose_name='тема')),
            ],
            options={
                'verbose_name': 'видеоролик',
                'verbose_name_plural': 'видеоролики',
            },
        ),
    ]
