# Generated by Django 3.2 on 2022-08-09 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID')),
                ('section_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FileInStorage',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID')),
                ('file_name', models.CharField(max_length=122)),
                ('file_type', models.CharField(max_length=122)),
                ('path', models.CharField(max_length=255)),
                ('load_date', models.DateField()),
                ('load_time', models.TimeField()),
                ('section', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='performancetech.section'
                )),
            ],
        ),
    ]
