# Generated by Django 3.2 on 2022-08-23 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performancetech', '0002_webpresentation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webpresentation',
            name='files',
        ),
        migrations.AddField(
            model_name='webpresentation',
            name='files_count',
            field=models.IntegerField(default=0),
        ),
    ]
