# Generated by Django 3.2 on 2022-08-23 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performancetech', '0003_auto_20220823_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='webpresentation',
            name='files',
            field=models.TextField(default=None),
        ),
    ]
