# Generated by Django 3.2 on 2022-08-25 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performancetech', '0004_webpresentation_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='webpresentation',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
