# Generated by Django 3.2 on 2022-08-25 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performancetech', '0005_webpresentation_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedFile',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID')),
                ('file_name', models.CharField(max_length=122)),
                ('file_type', models.CharField(max_length=122)),
                ('del_date', models.DateField()),
                ('del_time', models.TimeField()),
            ],
        ),
    ]
