# Generated by Django 3.2 on 2022-08-25 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('performancetech', '0007_loadedfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loadedfile',
            old_name='del_time',
            new_name='load_time',
        ),
    ]
