# Generated by Django 3.2 on 2022-08-29 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performancetech', '0008_rename_del_time_loadedfile_load_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_name', models.CharField(blank=True, max_length=50, null=True)),
                ('note_text', models.TextField(default=None)),
                ('creation_date', models.DateField()),
                ('creation_time', models.TimeField()),
            ],
        ),
    ]
