# Generated by Django 3.2 on 2022-08-29 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performancetech', '0009_usernote'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernote',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
